nationalarchives/da-transform-terraform-environments

deployments/variables.tf

DTE-124 propogate from int to staging

---

.gitignore
common/.terraform.lock.hcl
common/ecr.tf
common/event_rule.tf
common/files/parser-buildspec.yaml
common/iam.tf
common/lambda.tf
common/parser_pipeline_slack_alerts.py
common/sns.tf
common/variables.tf

Slack notification added for parser deployment

Slack notifications added for parser deployment

---

.gitignore
deployments/main.tf
deployments/variables.tf

 DTE-191: Add Step Function version info to metadata (test)

---

deployments/main.tf

Updates to receive and process bag step function.

DTE-218 receive and process bag step function update and tests

---

.gitignore
deployments/main.tf
deployments/variables.tf

This will trigger the test pipeline to create;
- SNS Topic (tre-in)
- SQS Queue (rapb-in) which will subscribe to tre-in topic
- Lambda Function (rapb-trigger) which will consume the message in rapb-in queue and trigger receive-and-process-bag 
step_function.

TEST-DTE-274

---

.gitignore
deployments/main.tf
deployments/variables.tf

This will trigger the test pipeline to create;
- SNS Topic (tre-in)
- SQS Queue (rapb-in) which will subscribe to tre-in topic
- Lambda Function (rapb-trigger) which will consume the message in rapb-in queue and trigger receive-and-process-bag
step_function.

INT-DTE-274

---

.gitignore
deployments/main.tf
deployments/variables.tf

This will trigger the test pipeline to create;
- SNS Topic (tre-in)
- SQS Queue (rapb-in) which will subscribe to tre-in topic
- Lambda Function (rapb-trigger) which will consume the message in rapb-in queue and trigger receive-and-process-bag
step_function.

STAGING-DTE-274

---

.gitignore
deployments/main.tf
deployments/variables.tf

This will trigger the test pipeline to create;
- SNS Topic (tre-in)
- SQS Queue (rapb-in) which will subscribe to tre-in topic
- Lambda Function (rapb-trigger) which will consume the message in rapb-in queue and trigger receive-and-process-bag
step_function.

PROD-DTE-274

---

deployments/main.tf

Use new TRE internal topic -> dev

---

deployments/main.tf

tre-data-bucket s3:GetObject and s3:ListBuckets permissions added for bagit-to-dri-sip function
log permisison added to bagit-to-dri-sip function
slack permission added to dri-preingest-sip-generation step-function

added sfn arn to common slack publishers

---

deployments/main.tf

Add internal topic ARN; remove whitespace

Feature/dte 276/v2 msg updates/test -> test

---

deployments/main.tf
deployments/variables.tf

feature/DTE-276/v2-msg-updates/int -> int

---

deployments/main.tf
deployments/variables.tf

feature/DTE-276/v2-msg-updates/staging -> staging

---

deployments/main.tf
deployments/variables.tf

feature/DTE-276/v2-msg-updates/prod -> prod

---

deployments/variables.tf

Feature/dte 345/batch size updates -> dev

---

deployments/variables.tf

Feature/dte 345/batch size updates -> test

---

deployments/variables.tf

Feature/dte 345/batch size updates -> int

---

deployments/variables.tf

Feature/dte 345/batch size updates -> staging

---

deployments/variables.tf

Feature/dte 345/batch size updates -> prod

---

README.md

Really just a branch to merge to `test`. This should trigger the test code-pipeline (pulling in changes on test branch of modules repo, where permission to publish to v1 "in" sqs is removed)

TDR-3694: a tweak to the readme 
